# -*- coding: utf-8 -*-
{
    'name': 'Hospital Management',
    'author': 'Abdelmoniem Hgagy',
    'summary':'Hospital Management System',
    'website':'https://portfolio-hgagy.vercel.app/',
    'version': '1.0',
    'sequence' :"-100",
    'category': 'Productivity',
   'description': """Hospital Management System""",
    'depends': ['base','sale','mail','report_xlsx'],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'wizard/create_appointment_view.xml',
        'wizard/appointment_report_view.xml',
        'wizard/appointment_report_fun_view.xml',
        'views/patient.xml',
        'views/kids_view.xml',
        'views/gender_view.xml',
        'views/sale.xml',
        'views/appointment_view.xml',
        'views/doctor_view.xml',
        'views/partner.xml',
        'report/report.xml',
        'report/report_template_card.xml',
        'report/report_wizard_template_appointment.xml',
        'report/report_wizard_template_appointment_func.xml',

    ],
    'demo': [ ],
    'installable': True,
    'application':True,
    'auto_install': False,
    'license': 'LGPL-3',
}
